services:
  db:
    image: mongo:6.0
    container_name: skud_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: skud_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: skud_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data: